version: "3"
services:
  student_ui:
    image: khaledwaled/a2_student_ui
    volumes:
      - ./data:/app/data
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  admin_ui:
    image: khaledwaled/a2_admin_ui
    volumes:
      - ./data:/app/data
